MVC_Agency/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MVC_Agency.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles ="SuperAdmin")]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MVC_Agency/Areas/Admin/Controllers/PortfolioController.cs
using Business.CustomExceptions;
using Business.Service.Abstracts;
using Core.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MVC_Agency.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles ="SuperAdmin")]
    public class PortfolioController : Controller
    {
        private readonly IPortfolioService _portfolioService;

        public PortfolioController(IPortfolioService portfolioService)
        {
            _portfolioService = portfolioService;
        }

        public IActionResult Index()
        {
            var portfolio = _portfolioService.GetAllPortfolio();
            return View(portfolio);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Portfolio portfolio)
        {
            if (!ModelState.IsValid) return View();

            try
            {
                _portfolioService.AddPortfolio(portfolio);
            }
            catch (EntityNullException ex)
            {
                ModelState.AddModelError(ex.V, ex.Message);
                return View();
            }
            catch (FileNulException ex)
            {
                ModelState.AddModelError(ex.V, ex.Message);
                return View();
            }
            catch (FileLengthException ex)
            {
                ModelState.AddModelError(ex.V, ex.Message);
                return View();
            }
            catch (ContentTypeException ex)
            {
                ModelState.AddModelError(ex.V, ex.Message);
                return View();
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }


            return RedirectToAction(nameof(Index));

        }
        public IActionResult Delete(int id)
        {
            if (!ModelState.IsValid) return View();
            try
            {
                _portfolioService.DeletePortfolio(id);
            }
            catch(FileNulException ex)
            {
                ModelState.AddModelError(ex.V, ex.Message);
                return View();

            }
            catch(EntityNullException ex)
            {
                ModelState.AddModelError(ex.V, ex.Message);
                return View();
            }
            return RedirectToAction(nameof(Index));
        }
       
        public IActionResult Update(int id)
        {
            var portofilio = _portfolioService.GetPortfolio(x => x.Id == id);
            if (portofilio == null) return View("Error");
            return View(portofilio);
        }
        [HttpPost]
        public IActionResult Update(Portfolio portfolio)
        {
            if (!ModelState.IsValid) return View();
            try
            {
                _portfolioService.UpdatePortfolio(portfolio.Id, portfolio);
            }catch(EntityNullException ex)
            {
                ModelState.AddModelError(ex.V, ex.Message);
                return View();
            }
            catch(FileLengthException ex)
            {
                ModelState.AddModelError(ex.V, ex.Message);
                return View();
            }
            catch(ContentTypeException ex)
            {
                ModelState.AddModelError(ex.V, ex.Message);
                return View();
            }
            catch(PhotoNotFoundException ex)
            {
                ModelState.AddModelError(ex.V, ex.Message);
                return View();
            }

            return RedirectToAction(nameof(Index));
        }

    }
}

MVC_Agency/Controllers/AccountController.cs
using Core.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MVC_Agency.DTOs.AccountDto;

namespace MVC_Agency.Controllers
{
    public class AccountController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public AccountController(UserManager<User> userManager, SignInManager<User> signInManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
        }

        public IActionResult Index()
        {
            return View();
        }

      

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]

        public async Task<IActionResult> Register(RegisterDto registerDto)
        {

            if(!ModelState.IsValid) return View();
            User user = new User()
            {
                Name = registerDto.Name,
                Surname = registerDto.Surname,
                Email = registerDto.Email,
                UserName = registerDto.Username,
            };
            var result = await _userManager.CreateAsync(user, registerDto.Password);
            if(!result.Succeeded)
            {
                foreach(var item in result.Errors)
                {
                    ModelState.AddModelError("", item.Description);
                }
                return View(registerDto);
            }
            await _signInManager.SignInAsync(user,false);
            return RedirectToAction("Index","Home");
        }

        public async Task<IActionResult> LogOut()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginDto loginDto)
        {
            if (!ModelState.IsValid) return View();
            var user = await _userManager.FindByNameAsync(loginDto.UserName);
            if(user == null)
            {
                ModelState.AddModelError("", "yoxdur istifadeci");
                return View();
            }
            var result = await _signInManager.PasswordSignInAsync(user,loginDto.Password,loginDto.IsConfirmed,false);
            return RedirectToAction("Index", "Home");
        }

        //public async  Task<IActionResult> CreateRole()
        //{
        //    IdentityRole role = new IdentityRole("SuperAdmin");
        //    IdentityRole role1 = new IdentityRole("Admin");
        //    IdentityRole role2 = new IdentityRole("Member");

        //    await _roleManager.CreateAsync(role);
        //    await _roleManager.CreateAsync(role1);
        //    await _roleManager.CreateAsync(role2);
        //    return Ok("Rollar Yarandiiiiiiiiiiii!!!!!!!!!");

        //}

        public async Task<IActionResult> AddRole()
        {
            var role = await _userManager.FindByNameAsync("ramazann.85");
            await _userManager.AddToRoleAsync(role, "SuperAdmin");

            return Ok("Roll verildiiiiii!!!!!!!!!!!");
        }
    }
}

MVC_Agency/Controllers/HomeController.cs
using Business.Service.Abstracts;
using Microsoft.AspNetCore.Mvc;

using System.Diagnostics;

namespace MVC_Agency.Controllers
{
    public class HomeController : Controller
    {
        
        private readonly IPortfolioService _portfolioService;

        public HomeController(IPortfolioService portfolioService)
        {
            _portfolioService = portfolioService;
        }

        public IActionResult Index()
        {
            var result =_portfolioService.GetAllPortfolio();
            return View(result);
        }

       
    }
}

MVC_Agency/Areas/Admin/Views/Portfolio/Create.cshtml
@using Core.Models

@model Portfolio

<div class="container">
    <form method="post" enctype="multipart/form-data">
    <div class="row">
    <div class="col-md-4">
        <label asp-for="Title">Title</label>
        <input asp-for="Title" />
        <span asp-validation-for="Title"></span>
    </div>
        <div class="col-md-4" >
        <label asp-for="Description">Description</label>
        <input asp-for="Description" />
        <span asp-validation-for="Description"></span>
    </div>
        <div class="col-md-4">
        <label asp-for="PhotoFile">PhotoFile</label>
        <input asp-for="PhotoFile" />
        <span asp-validation-for="PhotoFile"></span>
    </div>
    <div asp-validation-summary=All class="text-danger"></div>
    <button type="submit" class="btn btn-primary">Submit</button>

    </div>
    </form>
</div>

MVC_Agency/Areas/Admin/Views/Portfolio/Index.cshtml
@using Core.Models
@model List<Portfolio>

@{
    int count = 0;
}
<h1>
    Portfolios
    <a asp-action="Create" asp-controller="Portfolio" class="btn btn-dark"> Create</a>
</h1>
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Title</th>
            <th scope="col">Description</th>
            <th scope="col">Image</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model){
            count++;
            <tr>
            <th scope="row">@count</th>
            <td>@item.Title</td>
            <td>@item.Description</td>
            <td>
                <div style="width:100px">
                <img src="~/Upload/Portfolio/@item.ImgUrl" width="100%">
                    </div>
            </td>
            <td>
                    <a class="btn btn-danger" asp-action="Update" asp-controller="portfolio" asp-route-id=@item.Id>Update</a>
                    <a class="btn btn-primary" asp-action="Delete" asp-controller="portfolio" asp-route-id=@item.Id>Delete</a>
            </td>
        </tr>
        }
        
    </tbody>
</table>

MVC_Agency/Areas/Admin/Views/Portfolio/Update.cshtml
@using Core.Models

@model Portfolio

<div class="container">
    <form method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-md-4">
                <label asp-for="Title">Title</label>
                <input asp-for="Title" />
                <span asp-validation-for="Title"></span>
            </div>
            <div class="col-md-4">
                <label asp-for="Description">Description</label>
                <input asp-for="Description" />
                <span asp-validation-for="Description"></span>
            </div>
            <div class="col-md-4">
                <label asp-for="PhotoFile">PhotoFile</label>
                <input asp-for="PhotoFile" />
                <span asp-validation-for="PhotoFile"></span>
            </div>

            <button type="submit" class="btn btn-primary">Submit</button>

        </div>
    </form>
</div>